=== lzieger03/Portfolio-XML-DTD/dtd/ordersDtd.dtd
<!-- erstellen einer orderReview -->
<!ELEMENT orderOverview (order*)>
<!ATTLIST orderOverview 
    title CDATA #REQUIRED>

<!-- order -->
<!ELEMENT order (customer, address, pizza+)>
<!ATTLIST order 
    orderID ID #REQUIRED
    timeStamp CDATA #REQUIRED>

<!-- customer -->
<!ELEMENT customer (student?)>
<!ATTLIST customer 
    name CDATA #REQUIRED
    surname CDATA #REQUIRED
    isStudent CDATA #REQUIRED>
    
<!-- customer: student -->
<!ELEMENT student (matrikelNo, placeOfStudy)>
<!ELEMENT matrikelNo (#PCDATA)>
<!ELEMENT placeOfStudy (#PCDATA)>
<!ATTLIST placeOfStudy 
    country CDATA #REQUIRED>

<!-- address -->
<!ELEMENT address (street, houseNo, postalCode, city)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT houseNo (#PCDATA)>
<!ELEMENT postalCode (#PCDATA)>
<!ELEMENT city (#PCDATA)>

<!-- pizza -->
<!ELEMENT pizza (topping, extraRequests*)>
<!ATTLIST pizza 
    pizzaID ID #REQUIRED
    size CDATA #REQUIRED
    isVegi CDATA #IMPLIED>

<!-- pizza: topping -->
<!ELEMENT topping (salami | ham | cheese | mushrooms | olives | broccoli | nduja | arugola)*>
<!ELEMENT salami (#PCDATA)>
<!ATTLIST salami 
    spicy CDATA #REQUIRED>
<!ELEMENT ham (#PCDATA)>
<!ELEMENT cheese (#PCDATA)>
<!ELEMENT mushrooms (#PCDATA)>
<!ELEMENT olives (#PCDATA)>
<!ELEMENT broccoli (#PCDATA)>
<!ELEMENT nduja (#PCDATA)>
<!ELEMENT arugola (#PCDATA)>

<!-- pizza: extraRequests -->
<!ELEMENT extraRequests (#PCDATA)>

=== lzieger03/Portfolio-XML-DTD/xml/myOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE orderOverview SYSTEM "../dtd/ordersDtd.dtd">

<orderOverview title="All the orders">
    <order orderID="OR003" timeStamp="2023-10-26 13:17:45">
        <customer name="Lars" surname="Zieger" isStudent="yes">
            <student>
                <matrikelNo>4531095</matrikelNo>
                <placeOfStudy country="germany">DHBW Karlsruhe</placeOfStudy>
            </student>
        </customer>
        <address>
            <street>Teststraße</street>
            <houseNo>12</houseNo>
            <postalCode>32145</postalCode>
            <city>Testhausen</city>
        </address>
        <pizza pizzaID="PZ001" size="30cm">
            <topping>
                <cheese>Käse</cheese>
                <mushrooms>Pilze</mushrooms>
                <nduja>Nduja</nduja>
                <olives>Oliven</olives>
                <arugola>Ruccola</arugola>
            </topping>
            <extraRequests></extraRequests>
        </pizza>
    </order>
</orderOverview>

=== lzieger03/Portfolio-XML-DTD/xml/firstOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE orderOverview SYSTEM "../dtd/ordersDtd.dtd">

<orderOverview title="All the orders">
    <order orderID="OR001" timeStamp="2023-10-25 14:10:36">
        <customer name="Hermann" surname="Studymann" isStudent="yes">
            <student>
                <matrikelNo>41234567890</matrikelNo>
                <placeOfStudy country="germany">Karlsruhe</placeOfStudy>
            </student>
        </customer>
        <address>
            <street>Musterstraße</street>
            <houseNo>123</houseNo>
            <postalCode>12345</postalCode>
            <city>Musterstadt</city>
        </address>
        <pizza pizzaID="PZ001" size="30cm">
            <topping>
                <salami spicy="yes">Salami</salami>
                <ham>Schinken</ham>
                <cheese>Käse</cheese>
            </topping>
            <extraRequests>Bitte extra scharf</extraRequests>
        </pizza>
        <pizza pizzaID="PZ002" size="28cm">
            <topping>
                <salami spicy="no"></salami>
                <cheese>Käse</cheese>
                <mushrooms>Pilze</mushrooms>
            </topping>
            <extraRequests>Bitte keine Soße</extraRequests>
        </pizza>
        <pizza pizzaID="PZ003" size="46cm">
            <topping>
                <cheese>Käse</cheese>
                <mushrooms>Pilze</mushrooms>
                <mushrooms>Pilze</mushrooms>
            </topping>
            <extraRequests>Bitte extra viele Pilze</extraRequests>
        </pizza>
    </order>
</orderOverview>

=== lzieger03/Portfolio-XML-DTD/xml/secondOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE orderOverview SYSTEM "../dtd/ordersDtd.dtd">

<orderOverview title="All the orders">
    <order orderID="OR002" timeStamp="2023-10-26 12:07:32">
        <customer name="Claudia" surname="Nonstudent" isStudent="no">
        </customer>
        <address>
            <street>Gerlindestraße</street>
            <houseNo>25</houseNo>
            <postalCode>32145</postalCode>
            <city>Ausdenkhausen</city>
        </address>
        <pizza pizzaID="PZ001" size="30cm">
            <topping>
                <salami spicy="yes"></salami>
                <ham>Schinken</ham>
                <cheese>Käse</cheese>
                <mushrooms>Pilze</mushrooms>
            </topping>
            <extraRequests>Könnte ich bitte noch Oliven haben, aber nur die grünen</extraRequests>
        </pizza>
    </order>
</orderOverview>
